<?php
// SPDX-License-Identifier: GPL-3.0-or-later
defined('MOODLE_INTERNAL') || die();
$functions = [
    'local_lambanalytics_forum_posts' => [
        'classname' => 'local_lambanalytics\external\forum_posts',
        'methodname' => 'execute',
        'description' => 'Read bounded visible public post metadata with stored timestamps, without text or private replies.',
        'type' => 'read',
        'capabilities' => 'mod/forum:viewdiscussion,moodle/course:enrolreview',
        'services' => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'local_lambanalytics_forum_scope' => [
        'classname' => 'local_lambanalytics\external\forum_scope',
        'methodname' => 'execute',
        'description' => 'Revalidate exact discussion and group authority without returning posts or dates.',
        'type' => 'read',
        'capabilities' => 'mod/forum:viewdiscussion,moodle/course:enrolreview',
        'services' => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'local_lambanalytics_quiz_attempts' => [
        'classname' => 'local_lambanalytics\external\quiz_attempts',
        'methodname' => 'execute',
        'description' => 'Read a bounded permission-scoped page of raw quiz attempt metadata, without question content.',
        'type' => 'read',
        'capabilities' => 'mod/quiz:viewreports,moodle/course:enrolreview',
        'services' => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'local_lambanalytics_quiz_scope' => [
        'classname' => 'local_lambanalytics\external\quiz_scope',
        'methodname' => 'execute',
        'description' => 'Revalidate exact quiz report and population scope without retrieving attempts.',
        'type' => 'read',
        'capabilities' => 'mod/quiz:viewreports,moodle/course:enrolreview',
        'services' => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'local_lambanalytics_default_dates' => [
        'classname' => 'local_lambanalytics\external\default_dates',
        'methodname' => 'execute',
        'description' => 'Read fixed course-default assignment/quiz dates or revalidate exact saved module scope.',
        'type' => 'read',
        'capabilities' => 'mod/assign:grade,mod/quiz:viewreports',
        'services' => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'local_lambanalytics_completion_scope' => [
        'classname' => 'local_lambanalytics\external\completion_scope',
        'methodname' => 'execute',
        'description' => 'Revalidate progress-report and exact activity scope without collecting completion evidence.',
        'type' => 'read',
        'capabilities' => 'report/progress:view,moodle/course:enrolreview',
        'services' => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'local_lambanalytics_grade_scope' => [
        'classname' => 'local_lambanalytics\external\grade_scope',
        'methodname' => 'execute',
        'description' => 'Revalidate assignment grading and population permissions without reading grades.',
        'type' => 'read',
        'capabilities' => 'mod/assign:grade,moodle/course:enrolreview',
        'services' => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'local_lambanalytics_resource_scope' => [
        'classname' => 'local_lambanalytics\external\resource_scope',
        'methodname' => 'execute',
        'description' => 'Revalidate current course, group and resource permissions without querying event evidence.',
        'type' => 'read',
        'capabilities' => 'report/log:view,moodle/course:enrolreview',
        'services' => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'local_lambanalytics_resource_events' => [
        'classname' => 'local_lambanalytics\external\resource_events',
        'methodname' => 'execute',
        'description' => 'Read a bounded permission-scoped page of recorded course/resource views.',
        'type' => 'read',
        'capabilities' => 'report/log:view',
        'services' => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
];
