const text = {
 en: ['Learning scenarios','Learning scenario','Create','Title','Content','Save','Cancel','Edit','Remove','Duplicate','Set as default','Clear default','Default scenario','Empty scenario','Select scenario','Start conversation','Back','No learning scenario selected','Scenario unavailable','Remove this scenario? It will no longer be available for new conversations. Existing chat history stays.','Copy',"A learning scenario describes the situation you work in, so that LAMB AGENT can help you with it in mind: who you are as a creator, who your assistants are for, what they are for, what your audience already knows, and what you want to avoid. It is written as a description (\"The user is a teacher who…\"), in your own words, and you select it in any conversation where it applies. Two or three lines are enough to start. You can make it more concrete later: the vocabulary your course uses, or a knowledge base or assistant the agent may explore to learn your material. It is not a lesson plan, not a list of tasks for this chat, and students never see it.",'Ask the agent to help','Close','Unsaved changes. Discard them?'],
 es: ['Escenarios de aprendizaje','Escenario de aprendizaje','Crear','Título','Contenido','Guardar','Cancelar','Editar','Eliminar','Duplicar','Establecer como predeterminado','Quitar predeterminado','Escenario predeterminado','Escenario vacío','Seleccionar escenario','Iniciar conversación','Volver','Ningún escenario de aprendizaje seleccionado','Escenario no disponible','¿Eliminar este escenario? Ya no estará disponible para nuevas conversaciones. El historial de chat se conserva.','Copia',"Un escenario de aprendizaje describe la situación en la que trabajas, para que LAMB AGENT te ayude teniéndola presente: quién eres como creador, para quién son tus asistentes, para qué sirven, qué sabe ya tu público y qué quieres evitar. Se escribe como una descripción («El usuario es un profesor que…»), con tus palabras, y lo seleccionas en cualquier conversación donde se aplique. Con dos o tres líneas basta para empezar. Más adelante puedes concretarlo: el vocabulario que usa el curso, o una base de conocimiento o un asistente que el agente pueda explorar para conocer tu material. No es un plan de sesión, ni una lista de tareas para este chat, y los estudiantes nunca lo ven.",'Pedir ayuda al agente','Cerrar','Hay cambios sin guardar. ¿Descartarlos?'],
 ca: ['Escenaris d’aprenentatge','Escenari d’aprenentatge','Crear','Títol','Contingut','Desar','Cancel·lar','Editar','Eliminar','Duplicar','Establir com a predeterminat','Treure el predeterminat','Escenari predeterminat','Escenari buit','Seleccionar escenari','Iniciar conversa','Tornar','Cap escenari d’aprenentatge seleccionat','Escenari no disponible','Vols eliminar aquest escenari? Ja no estarà disponible per a noves converses. Es conserva l’historial del xat.','Còpia',"Un escenari d'aprenentatge descriu la situació en què treballes, perquè LAMB AGENT t'ajudi tenint-la present: qui ets com a creador, per a qui són els teus assistents, per a què serveixen, què sap ja el teu públic i què vols evitar. S'escriu com una descripció («L'usuari és un professor que…»), amb les teves paraules, i el selecciones a qualsevol conversa on s'apliqui. Amb dues o tres línies n'hi ha prou per començar. Més endavant el pots concretar: el vocabulari que fa servir el curs, o una base de coneixement o un assistent que l'agent pugui explorar per conèixer el teu material. No és un pla de sessió, ni una llista de tasques per a aquest xat, i els estudiants no el veuen mai.",'Demanar ajuda a l’agent','Tancar','Hi ha canvis sense desar. Els vols descartar?'],
 eu: ['Ikaskuntza-eszenatokiak','Ikaskuntza-eszenatokia','Sortu','Izenburua','Edukia','Gorde','Utzi','Editatu','Kendu','Bikoiztu','Lehenetsi','Lehenetsia kendu','Eszenatoki lehenetsia','Eszenatoki hutsa','Hautatu eszenatokia','Hasi elkarrizketa','Atzera','Ez dago ikaskuntza-eszenatokirik hautatuta','Eszenatokia ez dago erabilgarri','Eszenatoki hau kendu? Ez da elkarrizketa berrietarako erabilgarri egongo. Txataren historia gordeko da.','Kopia','Zure lanerako testuinguru iraunkorra: hartzaileak, helburua, aurretiko ezagutzak eta mugak. LAMB AGENTek laguntzaileak, edukiak eta probak egokitzeko erabiltzen du.','Agenteari laguntza eskatu','Itxi','Gorde gabeko aldaketak daude. Baztertu?']
};
const keys = ['plural','singular','create','title','content','save','cancel','edit','remove','duplicate','setDefault','clearDefault','default','empty','select','start','back','none','unavailable','confirmRemove','copy','hint','help','close','discard'];
const workspace = {
 en: {editWithAgent:'Edit with agent', remoteChanged:'A newer revision was saved. Your unsaved edits are preserved. Reload to review it before saving.', reload:'Reload saved version'},
 es: {editWithAgent:'Editar con el agente', remoteChanged:'Se ha guardado una versión más reciente. Tus cambios sin guardar se conservan. Recarga para revisarla antes de guardar.', reload:'Recargar versión guardada'},
 ca: {editWithAgent:'Editar amb l’agent', remoteChanged:'S’ha desat una versió més recent. Es conserven els teus canvis sense desar. Recarrega-la per revisar-la abans de desar.', reload:'Recarregar la versió desada'},
 eu: {editWithAgent:'Agentearekin editatu', remoteChanged:'Bertsio berriago bat gorde da. Gorde gabeko aldaketak mantendu dira. Kargatu berriro gorde aurretik berrikusteko.', reload:'Gordetako bertsioa berriz kargatu'}
};
export function scenarioText(locale) { return {...Object.fromEntries(keys.map((k,i)=>[k,(text[locale]||text.en)[i]])), ...(workspace[locale]||workspace.en)}; }
