const text = {
 en: ['Learning scenarios','Learning scenario','Create','Title','Content','Save','Cancel','Edit','Remove','Duplicate','Set as default','Clear default','Default scenario','Empty scenario','Select scenario','Start conversation','Back','No learning scenario selected','Scenario unavailable','Remove this scenario? It will no longer be available for new conversations. Existing chat history stays.','Copy','Lasting context for your work: audience, purpose, prior knowledge and constraints. LAMB AGENT uses it to help align your assistants, content and tests.','Ask the agent to help','Close','Unsaved changes. Discard them?'],
 es: ['Escenarios de aprendizaje','Escenario de aprendizaje','Crear','Título','Contenido','Guardar','Cancelar','Editar','Eliminar','Duplicar','Establecer como predeterminado','Quitar predeterminado','Escenario predeterminado','Escenario vacío','Seleccionar escenario','Iniciar conversación','Volver','Ningún escenario de aprendizaje seleccionado','Escenario no disponible','¿Eliminar este escenario? Ya no estará disponible para nuevas conversaciones. El historial de chat se conserva.','Copia','Contexto duradero para tu trabajo: público, propósito, conocimientos previos y limitaciones. LAMB AGENT lo usa para ayudarte a alinear asistentes, contenidos y pruebas.','Pedir ayuda al agente','Cerrar','Hay cambios sin guardar. ¿Descartarlos?'],
 ca: ['Escenaris d’aprenentatge','Escenari d’aprenentatge','Crear','Títol','Contingut','Desar','Cancel·lar','Editar','Eliminar','Duplicar','Establir com a predeterminat','Treure el predeterminat','Escenari predeterminat','Escenari buit','Seleccionar escenari','Iniciar conversa','Tornar','Cap escenari d’aprenentatge seleccionat','Escenari no disponible','Vols eliminar aquest escenari? Ja no estarà disponible per a noves converses. Es conserva l’historial del xat.','Còpia','Context durador per a la teva feina: públic, propòsit, coneixements previs i limitacions. LAMB AGENT l’utilitza per ajudar-te a alinear assistents, continguts i proves.','Demanar ajuda a l’agent','Tancar','Hi ha canvis sense desar. Els vols descartar?'],
 eu: ['Ikaskuntza-eszenatokiak','Ikaskuntza-eszenatokia','Sortu','Izenburua','Edukia','Gorde','Utzi','Editatu','Kendu','Bikoiztu','Lehenetsi','Lehenetsia kendu','Eszenatoki lehenetsia','Eszenatoki hutsa','Hautatu eszenatokia','Hasi elkarrizketa','Atzera','Ez dago ikaskuntza-eszenatokirik hautatuta','Eszenatokia ez dago erabilgarri','Eszenatoki hau kendu? Ez da elkarrizketa berrietarako erabilgarri egongo. Txataren historia gordeko da.','Kopia','Zure lanerako testuinguru iraunkorra: hartzaileak, helburua, aurretiko ezagutzak eta mugak. LAMB AGENTek laguntzaileak, edukiak eta probak egokitzeko erabiltzen du.','Agenteari laguntza eskatu','Itxi','Gorde gabeko aldaketak daude. Baztertu?']
};
const keys = ['plural','singular','create','title','content','save','cancel','edit','remove','duplicate','setDefault','clearDefault','default','empty','select','start','back','none','unavailable','confirmRemove','copy','hint','help','close','discard'];
const workspace = {
 en: {editWithAgent:'Edit with agent', remoteChanged:'A newer revision was saved. Your unsaved edits are preserved. Reload to review it before saving.', reload:'Reload saved version'},
 es: {editWithAgent:'Editar con el agente', remoteChanged:'Se ha guardado una versión más reciente. Tus cambios sin guardar se conservan. Recarga para revisarla antes de guardar.', reload:'Recargar versión guardada'},
 ca: {editWithAgent:'Editar amb l’agent', remoteChanged:'S’ha desat una versió més recent. Es conserven els teus canvis sense desar. Recarrega-la per revisar-la abans de desar.', reload:'Recarregar la versió desada'},
 eu: {editWithAgent:'Agentearekin editatu', remoteChanged:'Bertsio berriago bat gorde da. Gorde gabeko aldaketak mantendu dira. Kargatu berriro gorde aurretik berrikusteko.', reload:'Gordetako bertsioa berriz kargatu'}
};
export function scenarioText(locale) { return {...Object.fromEntries(keys.map((k,i)=>[k,(text[locale]||text.en)[i]])), ...(workspace[locale]||workspace.en)}; }
