"""baseline schema

Revision ID: 77979a6f7fd8
Revises:
Create Date: 2026-06-24 12:43:13.742764
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77979a6f7fd8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content_item_id', sa.String(), nullable=False),
    sa.Column('library_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('plugin_name', sa.String(), nullable=False),
    sa.Column('plugin_params', sa.Text(), nullable=True),
    sa.Column('source_path', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.create_index('idx_import_jobs_item', ['content_item_id'], unique=False)
        batch_op.create_index('idx_import_jobs_status', ['status'], unique=False)
        batch_op.create_index('idx_import_jobs_status_created', ['status', 'created_at'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('libraries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('import_config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_library_org_name')
    )
    op.create_table('content_folders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('library_id', sa.String(), nullable=False),
    sa.Column('parent_folder_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_folder_id'], ['content_folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library_id', 'parent_folder_id', 'name', name='uq_folder_sibling_name')
    )
    with op.batch_alter_table('content_folders', schema=None) as batch_op:
        batch_op.create_index('idx_content_folders_library', ['library_id'], unique=False)
        batch_op.create_index('idx_content_folders_parent', ['parent_folder_id'], unique=False)

    op.create_table('content_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('library_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('folder_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('base_path', sa.String(), nullable=False),
    sa.Column('original_path', sa.String(), nullable=True),
    sa.Column('full_markdown_path', sa.String(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('image_count', sa.Integer(), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('permalink_base', sa.String(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('import_plugin', sa.String(), nullable=False),
    sa.Column('import_params', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_stats', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['content_folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.create_index('idx_content_items_folder', ['folder_id'], unique=False)
        batch_op.create_index('idx_content_items_library', ['library_id'], unique=False)
        batch_op.create_index('idx_content_items_org', ['organization_id'], unique=False)
        batch_op.create_index('idx_content_items_status', ['status'], unique=False)

    op.create_table('content_images',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content_item_id', sa.String(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('llm_description', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_images', schema=None) as batch_op:
        batch_op.create_index('idx_content_images_item', ['content_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_images', schema=None) as batch_op:
        batch_op.drop_index('idx_content_images_item')

    op.drop_table('content_images')
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.drop_index('idx_content_items_status')
        batch_op.drop_index('idx_content_items_org')
        batch_op.drop_index('idx_content_items_library')
        batch_op.drop_index('idx_content_items_folder')

    op.drop_table('content_items')
    with op.batch_alter_table('content_folders', schema=None) as batch_op:
        batch_op.drop_index('idx_content_folders_parent')
        batch_op.drop_index('idx_content_folders_library')

    op.drop_table('content_folders')
    op.drop_table('libraries')
    op.drop_table('organizations')
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_index('idx_import_jobs_status_created')
        batch_op.drop_index('idx_import_jobs_status')
        batch_op.drop_index('idx_import_jobs_item')

    op.drop_table('import_jobs')
    # ### end Alembic commands ###
