// This file is auto-generated by scripts/generate-version.js
// Do not edit manually

export const VERSION_INFO = {
  "version": "0.5",
  "commit": "e4a54fe",
  "branch": "feature/issue#277/Architecture_Activity_Module_System_Extensible_LTI_App_Framework",
  "commitDate": "2026-02-27",
  "buildDate": "2026-03-02"
};
