// This file is auto-generated by scripts/generate-version.js
// Do not edit manually

export const VERSION_INFO = {
  "version": "0.5",
  "commit": "8fc4a574",
  "branch": "phase4-rama-experimental",
  "commitDate": "2026-03-23",
  "buildDate": "2026-03-24"
};
