"""baseline schema

Revision ID: 4d0c6668e3b9
Revises:
Create Date: 2026-06-24 12:32:39.522458
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d0c6668e3b9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('chunking_strategy', sa.String(), nullable=False),
    sa.Column('chunking_params', sa.Text(), nullable=True),
    sa.Column('embedding_vendor', sa.String(), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=False),
    sa.Column('embedding_endpoint', sa.String(), nullable=True),
    sa.Column('vector_db_backend', sa.String(), nullable=False),
    sa.Column('backend_collection_id', sa.String(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_collection_org_name')
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index('idx_collections_org', ['organization_id'], unique=False)
        batch_op.create_index('idx_collections_status', ['status'], unique=False)

    op.create_table('ingestion_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('documents_json', sa.Text(), nullable=False),
    sa.Column('documents_total', sa.Integer(), nullable=False),
    sa.Column('documents_processed', sa.Integer(), nullable=False),
    sa.Column('chunks_created', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.create_index('idx_ingestion_jobs_collection', ['collection_id'], unique=False)
        batch_op.create_index('idx_ingestion_jobs_status', ['status'], unique=False)
        batch_op.create_index('idx_ingestion_jobs_status_created', ['status', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.drop_index('idx_ingestion_jobs_status_created')
        batch_op.drop_index('idx_ingestion_jobs_status')
        batch_op.drop_index('idx_ingestion_jobs_collection')

    op.drop_table('ingestion_jobs')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index('idx_collections_status')
        batch_op.drop_index('idx_collections_org')

    op.drop_table('collections')
    # ### end Alembic commands ###
