// This file is auto-generated by scripts/generate-version.js
// Do not edit manually

export const VERSION_INFO = {
  "version": "0.6",
  "commit": "7e985a60",
  "branch": "lamba_refactor_merge_kvcache_v2_with_cost_management",
  "commitDate": "2026-06-16",
  "buildDate": "2026-06-15"
};
